replicaCount: 2

image:
  repository: your-username/cherie-frontend
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  API_BASE_URL: http://backend-service:5000

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 150m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: frontend-sa
