apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  DB_HOST: {{ .Values.env.DB_HOST }}
  DB_PORT: "{{ .Values.env.DB_PORT }}"
  REDIS_HOST: {{ .Values.env.REDIS_HOST }}
  REDIS_PORT: "{{ .Values.env.REDIS_PORT }}"
